### ISSUE TITLE
Feedback - Migration, Policies etc.

### ISSUE THREAD

**Issue by steph409** [Azure/terraform-azurerm-alz#1]
Hi guys,

I really like the idea to move the json archetype configurations & policies in a separate terraform provider, so that we can have input validation, type linting and naming for the configurations.

here are my two cents on the module
1. really looking forward to having type linting and input validation for the configurations
2. will there be a migration strategy from caf-enterprise scale terraform module to this one? how will they work together?
3. where are the resources defined, e.g. log analytics workspace and identities which do the remediation of the policies? will I need to pass in the log analytics workspace into every archetype where I have a policies with logs?
4. some initiatives have a lot of parameters. it would be amazing to have typelinting to overwrite the defaults for them.

BR,
Stephi

**Comment by matt-FFFFFF** [comment]
Thank you @steph409 for taking the time to read and feed back on the specification. It is very much appreciated.

In terms of your feedback:

> really looking forward to having type linting and input validation for the configurations

Thanks! We feel this was the correct approach for assignments, given the parameters are likely to come from the Terraform resource graph.

> will there be a migration strategy from caf-enterprise scale terraform module to this one? how will they work together?

Migration of management groups will be a re-deploy and move subscriptions. Migration of networking, LA workspace, etc will be either a state migration, or left alone in the old module. We are working on some automation for the state migration.

> where are the resources defined, e.g. log analytics workspace and identities which do the remediation of the policies? will I need to pass in the log analytics workspace into every archetype where I have a policies with logs?

Resources will be defined in separate modules, we are creating them now. There is one here https://github.com/Azure/terraform-azurerm-hubnetworking and we also have the alz management module completed. VWAN is in progress.

In terms of well known parameters, yes unfortunately these will have to be passed into each archetype data source. I do not think we can have references within provider blocks. I will test this and if we can move it into the provider block then we will do that.

> some initiatives have a lot of parameters. it would be amazing to have typelinting to overwrite the defaults for them.

We can investigate this. For built-in and ALZ default policy sets this could work, but not sure we could do this for custom policy sets.

**Comment by cveld** [comment]
@matt-FFFFFF are you (or the Azure on Terraform team as a whole) also working with Hashicorp to potentially extend the terraform expressiveness? E.g. by introducing base classes. In such a base class one could configure the central log analytics workspace. Another way of factorizing the resource declarations would be letting the provider having access to the full module scope. The provider could then first read the general settings resource declaration and then start processing the other resource declarions.

**Comment by matt-FFFFFF** [comment]
Closing as initial experimental version is released
